apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: nestjs
spec:
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
        - name: nest-backend
          image: studiounivers-backend:latest
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: nest-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: nest-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          envFrom:
            - secretRef:
                name: nestjs-secret
          ports:
            - containerPort: 3001
          resources:
            limits:
              memory: "64Mi"
              cpu: "250m"
