apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: "1000Mi"
              cpu: "250m"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
