name: backend-build-image-docker

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build backend image
        run: docker build ./backend --file Dockerfile --tag studiounivers-backend:$(date +%s)
